# Generated by Django 5.0 on 2024-08-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.UUIDField(db_comment='Unique article of the product. Used for searching and identifying the product.', db_index=True, verbose_name='Product Article'),
        ),
    ]
