# Generated by Django 5.0 on 2024-08-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=1, max_length=255, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
